#!/usr/bin/with-contenv bash

VPN_USER=${VPN_USER:-NOUSER}
VPN_PASS=${VPN_PASS:-NOPASSWORD}

echo "Creating vpn credentials"
echo "${VPN_USER}" > /config/openvpn-credentials.txt
echo "${VPN_PASS}" >> /config/openvpn-credentials.txt
chown 400 /config/openvpn-credentials.txt
