#!/usr/bin/with-contenv bash

if [ -e /config/defaultroute ]; then
  rm -f /config/defaultroute
fi

GW=$(ip r | grep default|awk '{print $3}')
LOCALSUBNET=$(ip r|grep link|awk '{print $1}')
echo "GW:${GW}" > /config/defaultroute
echo "LOCALSUBNET:${LOCALSUBNET}" >> /config/defaultroute

